name: Node CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build
      run: |
        npm ci
        npm run lint
        npm test
    - name: Run semantic-release
      run: npm run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage
      if: always()
