name: Node CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: ".nvmrc"
    - name: Build
      run: |
        npm ci
        npm run lint
        npm test
    - name: Run semantic-release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage
      if: always()
